### ISSUE TITLE
Match List By ID Parse Error

### ISSUE THREAD

**Issue by Burnett1** [Thangiee/Riot-API-Scala#1]
Trying out your library and I was unable to use RiotApi#matchListById. There are no tests for this call so it could be either.

It return the following error:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MappingException: No usable value for participants
No usable value for stats
No usable value for nodeCapture
Did not find value which can be converted into long]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
    at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
Caused by: org.json4s.package$MappingException: No usable value for participants
No usable value for stats
No usable value for nodeCapture
Did not find value which can be converted into long
    at org.json4s.reflect.package$.fail(package.scala:96) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
    at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:462) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
    at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
    at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.11.7.jar:na]
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[scala-library-2.11.7.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
    at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.7.jar:na]
```

``` scala
    RiotApi.matchByMatchId(1484558963) map { matchDet =>
      println(matchDet)
    }
```

**Comment by Thangiee** [comment]
Humm, I am trying to reproduce the error but when i used your example:

```scala
  RiotApi.matchByMatchId(1484558963)
```

I got a Bad(DataNotFound) i.e 404 and so i double checked the with the riot api website and I also got back a 404. (https://na.api.pvp.net/api/lol/na/v2.2/match/1484558963?api_key=456267a6-1777-4763-a77f-f3b1f06ed99d)

However, it did work when I tried an existing match id 
```scala
RiotApi.matchByMatchId(1931005045)
```

Just to be clear, are you using version 0.4.4 for this library?

If you keep on getting the error, could you try it with the riot api website and then post the json response you got from it. 

Thanks

**Comment by Burnett1** [comment]
Oops. I should of said it was EUW that I am trying from. Using the Riot API site I am able to execute the request with a successful json return. I am also able to print out the json if I modify your library to print out the json on request. It appears to be in the parsing of the match details object.

```
{"matchId":1484558963,"region":"EUW","platformId":"EUW1","matchMode":"CLASSIC","matchType":"MATCHED_GAME","matchCreation":1400615160487,"matchDuration":1176,"queueType":"RANKED_TEAM_3x3","mapId":10,"season":"SEASON2014","matchVersion":"4.7.0.305","participants":[{"teamId":100,"spell1Id":4,"spell2Id":14,"championId":58,"highestAchievedSeasonTier":"UNRANKED","timeline":{"creepsPerMinDeltas":{"zeroToTen":4.4},"xpPerMinDeltas":{"zeroToTen":334.9},"goldPerMinDeltas":{"zeroToTen":182.1},"damageTakenPerMinDeltas":{"zeroToTen":654.8},"role":"NONE","lane":"JUNGLE"},"stats":{"winner":false,"champLevel":10,"item0":3165,"item1":3117,"item2":0,"item3":0,"item4":0,"item5":0,"item6":0,"kills":0,"doubleKills":0,"tripleKills":0,"quadraKills":0,"pentaKills":0,"unrealKills":0,"largestKillingSpree":0,"deaths":9,"assists":0,"totalDamageDealt":43480,"totalDamageDealtToChampions":4768,"totalDamageTaken":17937,"largestCriticalStrike":0,"totalHeal":2864,"minionsKilled":78,"neutralMinionsKilled":0,"neutralMinionsKilledTeamJungle":0,"neutralMinionsKilledEnemyJungle":0,"goldEarned":4263,"goldSpent":5967,"combatPlayerScore":0,"objectivePlayerScore":0,"totalPlayerScore":0,"totalScoreRank":0,"magicDamageDealtToChampions":198,"physicalDamageDealtToChampions":4200,"trueDamageDealtToChampions":370,"visionWardsBoughtInGame":0,"sightWardsBoughtInGame":0,"magicDamageDealt":446,"physicalDamageDealt":42664,"trueDamageDealt":370,"magicDamageTaken":6730,"physicalDamageTaken":10986,"trueDamageTaken":220,"firstBloodKill":false,"firstBloodAssist":false,"firstTowerKill":false,"firstTowerAssist":false,"firstInhibitorKill":false,"firstInhibitorAssist":false,"inhibitorKills":0,"towerKills":0,"wardsPlaced":0,"wardsKilled":0,"largestMultiKill":0,"killingSprees":0,"totalUnitsHealed":1,"totalTimeCrowdControlDealt":12},"participantId":1},{"teamId":100,"spell1Id":4,"spell2Id":11,"championId":24,"highestAchievedSeasonTier":"UNRANKED","timeline":{"creepsPerMinDeltas":{"zeroToTen":0.2},"xpPerMinDeltas":{"zeroToTen":390.1},"goldPerMinDeltas":{"zeroToTen":255.6},"damageTakenPerMinDeltas":{"zeroToTen":567.0},"role":"DUO_SUPPORT","lane":"MIDDLE"},"stats":{"winner":false,"champLevel":10,"item0":1001,"item1":3144,"item2":3044,"item3":1042,"item4":1042,"item5":0,"item6":0,"kills":2,"doubleKills":0,"tripleKills":0,"quadraKills":0,"pentaKills":0,"unrealKills":0,"largestKillingSpree":0,"deaths":9,"assists":0,"totalDamageDealt":53955,"totalDamageDealtToChampions":8159,"totalDamageTaken":19612,"largestCriticalStrike":0,"totalHeal":58,"minionsKilled":17,"neutralMinionsKilled":46,"neutralMinionsKilledTeamJungle":45,"neutralMinionsKilledEnemyJungle":1,"goldEarned":4954,"goldSpent":4785,"combatPlayerScore":0,"objectivePlayerScore":0,"totalPlayerScore":0,"totalScoreRank":0,"magicDamageDealtToChampions":1453,"physicalDamageDealtToChampions":6706,"trueDamageDealtToChampions":0,"visionWardsBoughtInGame":0,"sightWardsBoughtInGame":0,"magicDamageDealt":6674,"physicalDamageDealt":41121,"trueDamageDealt":6160,"magicDamageTaken":4238,"physicalDamageTaken":14611,"trueDamageTaken":762,"firstBloodKill":false,"firstBloodAssist":false,"firstTowerKill":false,"firstTowerAssist":false,"firstInhibitorKill":false,"firstInhibitorAssist":false,"inhibitorKills":0,"towerKills":0,"wardsPlaced":0,"wardsKilled":0,"largestMultiKill":1,"killingSprees":0,"totalUnitsHealed":1,"totalTimeCrowdControlDealt":66},"participantId":2},{"teamId":100,"spell1Id":4,"spell2Id":14,"championId":131,"highestAchievedSeasonTier":"UNRANKED","timeline":{"creepsPerMinDeltas":{"zeroToTen":3.8},"xpPerMinDeltas":{"zeroToTen":370.1},"goldPerMinDeltas":{"zeroToTen":191.7},"damageTakenPerMinDeltas":{"zeroToTen":431.3},"role":"DUO_CARRY","lane":"MIDDLE"},"stats":{"winner":false,"champLevel":11,"item0":1001,"item1":2003,"item2":3090,"item3":1056,"item4":1052,"item5":0,"item6":0,"kills":1,"doubleKills":0,"tripleKills":0,"quadraKills":0,"pentaKills":0,"unrealKills":0,"largestKillingSpree":0,"deaths":9,"assists":1,"totalDamageDealt":58178,"totalDamageDealtToChampions":9842,"totalDamageTaken":15283,"largestCriticalStrike":0,"totalHeal":40,"minionsKilled":95,"neutralMinionsKilled":3,"neutralMinionsKilledTeamJungle":3,"neutralMinionsKilledEnemyJungle":0,"goldEarned":5174,"goldSpent":4905,"combatPlayerScore":0,"objectivePlayerScore":0,"totalPlayerScore":0,"totalScoreRank":0,"magicDamageDealtToChampions":8307,"physicalDamageDealtToChampions":1215,"trueDamageDealtToChampions":320,"visionWardsBoughtInGame":0,"sightWardsBoughtInGame":0,"magicDamageDealt":49528,"physicalDamageDealt":8329,"trueDamageDealt":320,"magicDamageTaken":7739,"physicalDamageTaken":7544,"trueDamageTaken":0,"firstBloodKill":false,"firstBloodAssist":false,"firstTowerKill":false,"firstTowerAssist":false,"firstInhibitorKill":false,"firstInhibitorAssist":false,"inhibitorKills":0,"towerKills":0,"wardsPlaced":0,"wardsKilled":0,"largestMultiKill":1,"killingSprees":0,"totalUnitsHealed":1,"totalTimeCrowdControlDealt":43},"participantId":3},{"teamId":200,"spell1Id":7,"spell2Id":4,"championId":127,"highestAchievedSeasonTier":"UNRANKED","timeline":{"creepsPerMinDeltas":{"zeroToTen":5.4},"xpPerMinDeltas":{"zeroToTen":425.70000000000005},"goldPerMinDeltas":{"zeroToTen":332.1},"damageTakenPerMinDeltas":{"zeroToTen":385.0},"role":"NONE","lane":"JUNGLE"},"stats":{"winner":true,"champLevel":13,"item0":1056,"item1":3020,"item2":3090,"item3":3136,"item4":1056,"item5":1052,"item6":0,"kills":6,"doubleKills":1,"tripleKills":0,"quadraKills":0,"pentaKills":0,"unrealKills":0,"largestKillingSpree":3,"deaths":2,"assists":14,"totalDamageDealt":76020,"totalDamageDealtToChampions":15745,"totalDamageTaken":9369,"largestCriticalStrike":0,"totalHeal":2396,"minionsKilled":116,"neutralMinionsKilled":5,"neutralMinionsKilledTeamJungle":0,"neutralMinionsKilledEnemyJungle":5,"goldEarned":9046,"goldSpent":7425,"combatPlayerScore":0,"objectivePlayerScore":0,"totalPlayerScore":0,"totalScoreRank":0,"magicDamageDealtToChampions":14522,"physicalDamageDealtToChampions":1222,"trueDamageDealtToChampions":0,"visionWardsBoughtInGame":0,"sightWardsBoughtInGame":0,"magicDamageDealt":62852,"physicalDamageDealt":13168,"trueDamageDealt":0,"magicDamageTaken":4343,"physicalDamageTaken":4956,"trueDamageTaken":70,"firstBloodKill":false,"firstBloodAssist":false,"firstTowerKill":false,"firstTowerAssist":false,"firstInhibitorKill":false,"firstInhibitorAssist":true,"inhibitorKills":0,"towerKills":1,"wardsPlaced":0,"wardsKilled":0,"largestMultiKill":2,"killingSprees":2,"totalUnitsHealed":3,"totalTimeCrowdControlDealt":142},"participantId":4},{"teamId":200,"spell1Id":4,"spell2Id":14,"championId":64,"highestAchievedSeasonTier":"UNRANKED","timeline":{"creepsPerMinDeltas":{"zeroToTen":1.3},"xpPerMinDeltas":{"zeroToTen":423.9},"goldPerMinDeltas":{"zeroToTen":346.8},"damageTakenPerMinDeltas":{"zeroToTen":605.3},"role":"NONE","lane":"JUNGLE"},"stats":{"winner":true,"champLevel":14,"item0":1055,"item1":3181,"item2":1055,"item3":3071,"item4":3117,"item5":3044,"item6":0,"kills":12,"doubleKills":1,"tripleKills":0,"quadraKills":0,"pentaKills":0,"unrealKills":0,"largestKillingSpree":11,"deaths":1,"assists":8,"totalDamageDealt":89313,"totalDamageDealtToChampions":14099,"totalDamageTaken":16400,"largestCriticalStrike":0,"totalHeal":2906,"minionsKilled":31,"neutralMinionsKilled":70,"neutralMinionsKilledTeamJungle":47,"neutralMinionsKilledEnemyJungle":23,"goldEarned":9350,"goldSpent":8280,"combatPlayerScore":0,"objectivePlayerScore":0,"totalPlayerScore":0,"totalScoreRank":0,"magicDamageDealtToChampions":2820,"physicalDamageDealtToChampions":10639,"trueDamageDealtToChampions":640,"visionWardsBoughtInGame":0,"sightWardsBoughtInGame":0,"magicDamageDealt":22226,"physicalDamageDealt":66447,"trueDamageDealt":640,"magicDamageTaken":4177,"physicalDamageTaken":11973,"trueDamageTaken":250,"firstBloodKill":true,"firstBloodAssist":false,"firstTowerKill":false,"firstTowerAssist":false,"firstInhibitorKill":false,"firstInhibitorAssist":false,"inhibitorKills":0,"towerKills":1,"wardsPlaced":0,"wardsKilled":0,"largestMultiKill":2,"killingSprees":1,"totalUnitsHealed":1,"totalTimeCrowdControlDealt":313},"participantId":5},{"teamId":200,"spell1Id":14,"spell2Id":4,"championId":86,"highestAchievedSeasonTier":"UNRANKED","timeline":{"creepsPerMinDeltas":{"zeroToTen":5.1},"xpPerMinDeltas":{"zeroToTen":433.2},"goldPerMinDeltas":{"zeroToTen":270.6},"damageTakenPerMinDeltas":{"zeroToTen":513.6},"role":"SOLO","lane":"MIDDLE"},"stats":{"winner":true,"champLevel":14,"item0":1054,"item1":3047,"item2":3071,"item3":3068,"item4":1028,"item5":2003,"item6":0,"kills":7,"doubleKills":1,"tripleKills":0,"quadraKills":0,"pentaKills":0,"unrealKills":0,"largestKillingSpree":7,"deaths":0,"assists":7,"totalDamageDealt":75828,"totalDamageDealtToChampions":11862,"totalDamageTaken":10657,"largestCriticalStrike":0,"totalHeal":270,"minionsKilled":124,"neutralMinionsKilled":5,"neutralMinionsKilledTeamJungle":3,"neutralMinionsKilledEnemyJungle":2,"goldEarned":8450,"goldSpent":7805,"combatPlayerScore":0,"objectivePlayerScore":0,"totalPlayerScore":0,"totalScoreRank":0,"magicDamageDealtToChampions":1298,"physicalDamageDealtToChampions":10222,"trueDamageDealtToChampions":342,"visionWardsBoughtInGame":0,"sightWardsBoughtInGame":0,"magicDamageDealt":3591,"physicalDamageDealt":71895,"trueDamageDealt":342,"magicDamageTaken":1438,"physicalDamageTaken":8849,"trueDamageTaken":370,"firstBloodKill":false,"firstBloodAssist":false,"firstTowerKill":false,"firstTowerAssist":false,"firstInhibitorKill":true,"firstInhibitorAssist":false,"inhibitorKills":1,"towerKills":1,"wardsPlaced":0,"wardsKilled":0,"largestMultiKill":2,"killingSprees":1,"totalUnitsHealed":1,"totalTimeCrowdControlDealt":67},"participantId":6}],"participantIdentities":[{"participantId":1,"player":{"summonerId":23880959,"summonerName":"Grandeffect","matchHistoryUri":"/v1/stats/player_history/EUW1/28197566","profileIcon":539}},{"participantId":2,"player":{"summonerId":25574729,"summonerName":"rAEgym","matchHistoryUri":"/v1/stats/player_history/EUW1/30003233","profileIcon":654}},{"participantId":3,"player":{"summonerId":24277040,"summonerName":"Lowacin","matchHistoryUri":"/v1/stats/player_history/EUW1/28696699","profileIcon":11}},{"participantId":4,"player":{"summonerId":39369037,"summonerName":"Sphreez","matchHistoryUri":"/v1/stats/player_history/EUW1/41531921","profileIcon":610}},{"participantId":5,"player":{"summonerId":38271671,"summonerName":"iluvchicken","matchHistoryUri":"/v1/stats/player_history/EUW1/40908209","profileIcon":663}},{"participantId":6,"player":{"summonerId":40787484,"summonerName":"KnobRob","matchHistoryUri":"/v1/stats/player_history/EUW1/200204301","profileIcon":579}}],"teams":[{"teamId":100,"winner":false,"firstBlood":false,"firstTower":false,"firstInhibitor":false,"firstBaron":false,"firstDragon":false,"towerKills":0,"inhibitorKills":0,"baronKills":0,"dragonKills":0,"vilemawKills":0,"dominionVictoryScore":0,"bans":[{"championId":106,"pickTurn":1},{"championId":36,"pickTurn":3},{"championId":59,"pickTurn":5}]},{"teamId":200,"winner":true,"firstBlood":true,"firstTower":true,"firstInhibitor":true,"firstBaron":false,"firstDragon":false,"towerKills":4,"inhibitorKills":1,"baronKills":0,"dragonKills":0,"vilemawKills":0,"dominionVictoryScore":0,"bans":[{"championId":23,"pickTurn":2},{"championId":31,"pickTurn":4},{"championId":114,"pickTurn":6}]}]}
```

**Comment by Thangiee** [comment]
This also works for me.
```scala
  RiotApi.matchByMatchId(1484558963, reg = "euw") match {
    case Good(matchDetail) => print(matchDetail)
    case Bad(e) => println(e)
  }
```
```
MatchDetail(10,1400615160487,1176,1484558963,CLASSIC,MATCHED_GAME,4.7.0.305,List(ParticipantIdentity(1,Player(/v1/stats/player_history/EUW1/28197566,539,23880959,Grandeffect)), ParticipantIdentity(2,Player(/v1/stats/player_history/EUW1/30003233,654,25574729,rAEgym)), ParticipantIdentity(3,Player(/v1/stats/player_history/EUW1/28696699,11,24277040,Lowacin)), ParticipantIdentity(4,Player(/v1/stats/player_history/EUW1/41531921,610,39369037,Sphreez)), ParticipantIdentity(5,Player(/v1/stats/player_history/EUW1/40908209,663,38271671,iluvchicken)), ParticipantIdentity(6,Player(/v1/stats/player_history/EUW1/200204301,579,40787484,KnobRob))),List(Participant(58,UNRANKED,List(),1,List(),4,14,ParticipantStats(0,10,0,9,0,false,false,false,false,false,false,4263,5967,0,3165,3117,0,0,0,0,0,0,0,0,0,0,446,198,6730,78,0,0,0,0,0,0,0,0,0,42664,4200,10986,0,0,0,43480,4768,17937,2864,0,0,12,1,0,0,370,370,220,0,0,0,0,false),100,ParticipantTimeline(ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,4.4),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,654.8),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,182.1),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),JUNGLE,NONE,ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,334.9))), Participant(24,UNRANKED,List(),2,List(),4,11,ParticipantStats(0,10,0,9,0,false,false,false,false,false,false,4954,4785,0,1001,3144,3044,1042,1042,0,0,0,2,0,0,1,6674,1453,4238,17,46,1,45,0,0,0,0,0,0,41121,6706,14611,0,0,0,53955,8159,19612,58,0,0,66,1,0,0,6160,0,762,0,0,0,0,false),100,ParticipantTimeline(ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.2),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,567.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,255.6),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),MIDDLE,DUO_SUPPORT,ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,390.1))), Participant(131,UNRANKED,List(),3,List(),4,14,ParticipantStats(1,11,0,9,0,false,false,false,false,false,false,5174,4905,0,1001,2003,3090,1056,1052,0,0,0,1,0,0,1,49528,8307,7739,95,3,0,3,0,0,0,0,0,0,8329,1215,7544,0,0,0,58178,9842,15283,40,0,0,43,1,0,0,320,320,0,0,0,0,0,false),100,ParticipantTimeline(ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,3.8),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,431.3),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,191.7),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),MIDDLE,DUO_CARRY,ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,370.1))), Participant(127,UNRANKED,List(),4,List(),7,4,ParticipantStats(14,13,0,2,1,false,false,true,false,false,false,9046,7425,0,1056,3020,3090,3136,1056,1052,0,2,6,0,3,2,62852,14522,4343,116,5,5,0,0,0,0,0,0,0,13168,1222,4956,0,0,0,76020,15745,9369,2396,0,0,142,3,1,0,0,0,70,0,0,0,0,true),200,ParticipantTimeline(ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,5.4),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,385.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,332.1),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),JUNGLE,NONE,ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,425.70000000000005))), Participant(64,UNRANKED,List(),5,List(),4,14,ParticipantStats(8,14,0,1,1,false,true,false,false,false,false,9350,8280,0,1055,3181,1055,3071,3117,3044,0,1,12,0,11,2,22226,2820,4177,31,70,23,47,0,0,0,0,0,0,66447,10639,11973,0,0,0,89313,14099,16400,2906,0,0,313,1,1,0,640,640,250,0,0,0,0,true),200,ParticipantTimeline(ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,1.3),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,605.3),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,346.8),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),JUNGLE,NONE,ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,423.9))), Participant(86,UNRANKED,List(),6,List(),14,4,ParticipantStats(7,14,0,0,1,false,false,false,true,false,false,8450,7805,1,1054,3047,3071,3068,1028,2003,0,1,7,0,7,2,3591,1298,1438,124,5,2,3,0,0,0,0,0,0,71895,10222,8849,0,0,0,75828,11862,10657,270,0,0,67,1,1,0,342,342,370,0,0,0,0,true),200,ParticipantTimeline(ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,5.1),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,513.6),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,270.6),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),MIDDLE,SOLO,ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,0.0),ParticipantTimelineData(0.0,0.0,0.0,433.2)))),EUW1,RANKED_TEAM_3x3,EUW,SEASON2014,List(Team(List(BannedChampion(106,1), BannedChampion(36,3), BannedChampion(59,5)),0,0,0,false,false,false,false,false,0,100,0,0,false), Team(List(BannedChampion(23,2), BannedChampion(31,4), BannedChampion(114,6)),0,0,0,false,true,false,true,true,1,200,4,0,true)),Timeline(0,List()))
```

Are you on version 0.4.4?

Are you using any build tool like SBT? 
If you are using SBT could you try to importing this library through it?
Assuming that you were using this library by just downloading the jar and adding it to your project.
Delete the jar and add this to your build.sbt file:

```scala
resolvers += "jcenter" at "https://jcenter.bintray.com/"

libraryDependencies ++= Seq(
  "com.github.thangiee" %% "riot-api-scala" % "0.4.4"
) 
```

**Comment by Burnett1** [comment]
Yeah I am using SBT with the play framework. I have changed it to use the remote dependency now and it has worked. I dont know why that was an issue though cause I first tried manually compiling it on my side and then using the sources in my project directly using the latest files on github.
